#!/usr/bin/zsh

# Locale
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# Term
export TERM="xterm-256color"

# Default Editor
export EDITOR="nvim"

# Default Pager
export PAGER="less"

# Oh My Zsh.
export ZSH="$HOME/.oh-my-zsh"

# bat theme
export BAT_THEM="TwoDark"

# Default username
export DEFAULT_USER="ccatlett2000"
